version: "3"
services:
  db:
    image: postgres:13
    restart: always
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpw
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: